#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative "../../lib/relay"
require "optparse"
require "rbconfig"

DEFAULT_BIND = "http://0.0.0.0:9292"
DEFAULT_TRANSPORT = "net_http_persistent"

##
# utils
def option_parser(bind, transport)
  OptionParser.new do |o|
    o.banner = "Usage: relay start [OPTIONS] [URL]"
    o.on("--transport TRANSPORT", "curb, net_http, or net_http_persistent.") { transport.replace(_1) }
    o.on("--bind URL", "Bind Falcon to a URL") { bind.replace(_1) }
  end
end

##
# main
def main(argv)
  bind = DEFAULT_BIND.dup
  transport = DEFAULT_TRANSPORT.dup
  option_parser(bind, transport).parse!(argv)
  bind = argv.shift || bind
  Dir.chdir(Relay.root) do
    ENV["RELAY_TRANSPORT"] = transport
    exec RbConfig.ruby, "-S", "falcon", "serve", "--bind", bind
  end
end

excode = catch(:exit) {
  main(ARGV)
  0
}
exit excode
