name: Relay

on:
  push:

jobs:
  test:
    name: Relay
    runs-on: ubuntu-latest
    env:
      RACK_ENV: test
      SESSION_SECRET: 0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef

    steps:
      - name: Dependencies
        run: apt install libcurl-dev

      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true

      - name: Set up database
        run: bundle exec relay bootstrap

      - name: Run Rubocop
        run: bundle exec rake rubocop

      - name: Run tests
        run: bundle exec rake test
